import { Link } from "@/lib/spa-router";
import { ArrowRight, Target, Flame, History, Award } from "lucide-react";
import aboutCraftsman from "@/assets/about-craftsman.jpg";

export default function AboutPage() {
  return (
    <div>
      <section className="bg-primary py-20 text-center text-primary-foreground md:py-28 bg-heritage-pattern">
        <div className="max-w-4xl mx-auto px-4"><h1 className="font-heading text-4xl font-bold md:text-5xl lg:text-6xl">Chhatrapati&apos;s Legacy in Every Creation</h1><div className="w-24 h-1 bg-gold mx-auto mt-4" /><p className="mt-6 text-lg font-display italic opacity-90">India&apos;s premier studio for authentic statues of Chhatrapati Shivaji Maharaj and Maratha weapons.</p></div>
      </section>
      <section className="py-16 md:py-24"><div className="w-full px-4"><div className="grid grid-cols-1 items-center gap-12 md:grid-cols-2"><div className="rounded-lg overflow-hidden shadow-heritage"><img src={aboutCraftsman} alt="Artisan at work" className="w-full h-96 object-cover" /></div><div><span className="text-gold font-heading text-sm uppercase tracking-widest">Managing Director</span><h2 className="font-heading text-3xl font-bold text-foreground mt-2">Shivrayart</h2><div className="w-16 h-1 bg-gold mt-3" /><p className="mt-6 text-muted-foreground leading-relaxed">With a deep-rooted passion for preserving India&apos;s martial heritage, Shivrayart bridges the gap between history and modern craftsmanship.</p></div></div></div></section>
      <section className="py-16 md:py-24 bg-card bg-heritage-pattern"><div className="w-full px-4"><div className="text-center mb-12"><h2 className="font-heading text-3xl md:text-4xl font-bold">Our Mission</h2><div className="w-24 h-1 bg-gold mx-auto mt-3" /></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{[{ icon: Target, title: "Historical Precision", desc: "Every detail follows documented accounts of Maratha warriors' equipment." }, { icon: Flame, title: "Warrior's Spirit", desc: "Infusing each creation with the dedication of our ancestors." }, { icon: History, title: "Cultural Continuity", desc: "Connecting modern generations with martial traditions." }, { icon: Award, title: "Artisanal Excellence", desc: "Employing traditional techniques passed down through generations." }].map((item) => <div key={item.title} className="bg-background rounded-lg p-6 text-center shadow-heritage border border-border"><div className="w-14 h-14 mx-auto rounded-full bg-primary/10 flex items-center justify-center mb-4"><item.icon className="w-6 h-6 text-gold" /></div><h3 className="font-heading text-base font-semibold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.desc}</p></div>)}</div></div></section>
      <section className="py-16 bg-primary text-primary-foreground text-center"><div className="max-w-3xl mx-auto px-4"><h2 className="font-heading text-3xl font-bold">Explore Our Collections</h2><Link to="/products" className="mt-8 inline-flex items-center gap-2 bg-gold text-gold-foreground px-8 py-3.5 rounded-md font-heading text-sm font-semibold uppercase tracking-wider">Shop Now <ArrowRight className="w-4 h-4" /></Link></div></section>
    </div>
  );
}
